# Generated by Django 3.2.25 on 2026-05-16 04:28

import apps.document_control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Category Code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Standard Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Document Number')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('REVIEW', 'Under Review'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('site', models.CharField(default='Maintenance 2nd site', max_length=100, verbose_name='Site/Location')),
                ('next_review_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Next Review Date')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_control.documentcategory')),
                ('preparer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_documents', to=settings.AUTH_USER_MODEL, verbose_name='Prepared By')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
                ('standard_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_control.standardtype')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=20, verbose_name='Version/Revision')),
                ('file', models.FileField(upload_to=apps.document_control.models.document_upload_path, verbose_name='File Attachment')),
                ('revision_history', models.TextField(blank=True, verbose_name='Revision History')),
                ('effective_date', models.DateField(verbose_name='Effective Date')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document_control.document')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'unique_together': {('document', 'version_number')},
            },
        ),
    ]
