# Generated by Django 3.2.25 on 2026-05-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('TRAINING', 'Training'), ('INTERNAL_AUDIT', 'Internal Audit'), ('EXTERNAL_AUDIT', 'External Audit'), ('MANAGEMENT_REVIEW', 'Management Review')], db_index=True, max_length=50, verbose_name='Activity Type')),
                ('title', models.CharField(max_length=255, verbose_name='Activity Title')),
                ('scheduled_date', models.DateField(db_index=True, verbose_name='Scheduled Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('responsible_person', models.CharField(max_length=100, verbose_name='Responsible Person')),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['scheduled_date'],
            },
        ),
    ]
