# Generated by Django 3.2.25 on 2026-05-16 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='standard_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='document_control.standardtype', verbose_name='Related Standard'),
        ),
    ]
