# Generated by Django 3.2.25 on 2026-05-16 07:04

import apps.document_control.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0003_schedule_standard_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=apps.document_control.models.schedule_upload_path, verbose_name='Attachment File')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='File Description')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='document_control.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Attachment',
                'verbose_name_plural': 'Schedule Attachments',
            },
        ),
    ]
