# Generated by Django 3.2.25 on 2026-05-16 12:18

import apps.document_control.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_control', '0004_scheduleattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'เอกสาร', 'verbose_name_plural': 'เอกสารทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'verbose_name': 'หมวดหมู่เอกสาร', 'verbose_name_plural': 'หมวดหมู่เอกสาร'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'verbose_name': 'เวอร์ชันเอกสาร', 'verbose_name_plural': 'เวอร์ชันเอกสารทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['scheduled_date'], 'verbose_name': 'กำหนดการ', 'verbose_name_plural': 'กำหนดการทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='scheduleattachment',
            options={'verbose_name': 'ไฟล์แนบกำหนดการ', 'verbose_name_plural': 'ไฟล์แนบกำหนดการทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='standardtype',
            options={'verbose_name': 'ระบบมาตรฐาน', 'verbose_name_plural': 'ระบบมาตรฐาน'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='training_schedules', to='document_control.Document', verbose_name='เอกสารที่เกี่ยวข้องกับการอบรม'),
        ),
        migrations.AlterField(
            model_name='document',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_documents', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_control.documentcategory', verbose_name='หมวดหมู่เอกสาร'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='เลขที่เอกสาร'),
        ),
        migrations.AlterField(
            model_name='document',
            name='next_review_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='วันทบทวนครั้งถัดไป'),
        ),
        migrations.AlterField(
            model_name='document',
            name='preparer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prepared_documents', to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัดทำ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ทบทวน'),
        ),
        migrations.AlterField(
            model_name='document',
            name='site',
            field=models.CharField(default='Maintenance 2nd site', max_length=100, verbose_name='ไซต์/สถานที่'),
        ),
        migrations.AlterField(
            model_name='document',
            name='standard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document_control.standardtype', verbose_name='ระบบมาตรฐาน'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'ฉบับร่าง'), ('PUBLISHED', 'ประกาศใช้'), ('REVIEW', 'รอการทบทวน'), ('CANCELLED', 'ยกเลิก')], db_index=True, default='DRAFT', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ชื่อเอกสาร'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='รหัสหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อหมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='document_control.document', verbose_name='เอกสาร'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='effective_date',
            field=models.DateField(verbose_name='วันที่มีผลบังคับใช้'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=apps.document_control.models.document_upload_path, verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='revision_history',
            field=models.TextField(blank=True, verbose_name='ประวัติการแก้ไข'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.CharField(max_length=20, verbose_name='เวอร์ชัน/การแก้ไข'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='activity_type',
            field=models.CharField(choices=[('TRAINING', 'การฝึกอบรม'), ('INTERNAL_AUDIT', 'การตรวจติดตามภายใน'), ('EXTERNAL_AUDIT', 'การตรวจติดตามภายนอก'), ('MANAGEMENT_REVIEW', 'การทบทวนฝ่ายบริหาร')], db_index=True, max_length=50, verbose_name='ประเภทกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='responsible_person',
            field=models.CharField(max_length=100, verbose_name='ผู้รับผิดชอบ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduled_date',
            field=models.DateField(db_index=True, verbose_name='วันที่กำหนด'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='standard_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='document_control.standardtype', verbose_name='มาตรฐานที่เกี่ยวข้อง'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'ตามแผน'), ('COMPLETED', 'ดำเนินการเสร็จสิ้น'), ('CANCELLED', 'ยกเลิก')], default='PLANNED', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ชื่อกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='scheduleattachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='รายละเอียดไฟล์'),
        ),
        migrations.AlterField(
            model_name='scheduleattachment',
            name='file',
            field=models.FileField(upload_to=apps.document_control.models.schedule_upload_path, verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='scheduleattachment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='document_control.schedule', verbose_name='กำหนดการ'),
        ),
        migrations.AlterField(
            model_name='standardtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AlterField(
            model_name='standardtype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='ชื่อมาตรฐาน'),
        ),
    ]
