# Generated by Django 3.2.25 on 2026-05-16 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_control', '0005_auto_20260516_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อแผนก')),
            ],
            options={
                'verbose_name': 'แผนก',
                'verbose_name_plural': 'แผนกทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสพนักงาน')),
                ('first_name', models.CharField(max_length=100, verbose_name='ชื่อ')),
                ('last_name', models.CharField(max_length=100, verbose_name='นามสกุล')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='ตำแหน่ง')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='document_control.department', verbose_name='แผนก')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงานทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_attended', models.BooleanField(default=True, verbose_name='เข้าอบรม')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='คะแนน')),
                ('result', models.CharField(choices=[('PASS', 'ผ่าน'), ('FAIL', 'ไม่ผ่าน'), ('PENDING', 'รอผล')], default='PENDING', max_length=10, verbose_name='ผลการทดสอบ')),
                ('remark', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='document_control.employee', verbose_name='พนักงาน')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='document_control.schedule', verbose_name='รายการอบรม')),
            ],
            options={
                'verbose_name': 'บันทึกการอบรมรายบุคคล',
                'verbose_name_plural': 'บันทึกการอบรมรายบุคคล',
                'unique_together': {('schedule', 'employee')},
            },
        ),
    ]
